# Generated by Django 4.1.7 on 2023-02-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
