# Generated by Django 4.1.7 on 2023-02-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_alter_quiz_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
