# Generated by Django 4.1.7 on 2023-02-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0003_alter_quiz_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty_level',
            field=models.CharField(max_length=50),
        ),
    ]
