# Generated by Django 4.1.7 on 2023-02-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0004_alter_quiz_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.IntegerField(default=0),
        ),
    ]
