# Generated by Django 4.1.6 on 2023-02-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0006_quiz_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty_level',
            field=models.CharField(choices=[('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], default='pending', max_length=10),
        ),
    ]
